GET http://localhost:3000/products

###
GET http://localhost:3000/products/61520ff7e5f1af18a0b8eca7
###
POST http://localhost:3000/add-product
x-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNGRjMzE3YWZiODA0MTA1MGE2NjE1ZSIsInVzZXJuYW1lIjoiYWRtaW4iLCJpc19BZG1pbiI6dHJ1ZSwiaWF0IjoxNjMyNzQ3NTEyLCJleHAiOjE2MzI3NDgxMTJ9.7x_jmGOjYS1bOG3vVxL4VBoAzdHO6aRvyaHt4xW0KfQ
Content-Type: application/json

{
  "title": "iPhone 13 Pro Max",
  "description": "Hệ thống camera chuyên nghiệp tiên tiến nhất từng có trên iPhone; Màn hình Super Retina XDR với ProMotion; một bước nhảy vọt về tuổi thọ pin; A15 Bionic, chip nhanh nhất trong điện thoại thông minh; trải nghiệm 5G tiên tiến; và nhiều hơn nữa",
  "price": "23999000",
  "sale": "100",
  "color": ["6151f3f988d41f333ac14866", "6151f3f988d41f333ac14866"],
  "config": ["614dcd52de51a05e8ae15ff9", "614dcd66de51a05e8ae15ffd"],
  "category": "614dcfa3c56a9c08e991476b",
  "stock": "200",
  "content": "iPhone 13 Pro Max ra mắt mang đến nhiều tính năng được mong đợi như màn hình ProMotion 120 Hz, máy ảnh được nâng cấp và có lẽ ấn tượng nhất là thời lượng pin tăng đáng kể. Trong bài viết này, chúng ta cùng xem xét sự khác biệt về thiết kế, ưu điểm của chip Apple A15 mới hơn, mọi thứ mới xung quanh camera và cuối cùng là thời lượng pin.",
  "image": "Apple iMac 27_ Mockup.png"
}

###
DELETE http://localhost:3000/products/6151c2cdaecbc23398b11c20
x-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNGRjMzE3YWZiODA0MTA1MGE2NjE1ZSIsInVzZXJuYW1lIjoiYWRtaW4iLCJpc19BZG1pbiI6dHJ1ZSwiaWF0IjoxNjMyNzQ4ODY2LCJleHAiOjE2MzI3NDk0NjZ9.bnXdWkdDdgXMBV14P-SH5buOQcwH64pr7lXBhE11X50

